version: "3.9"

services:
  frontend:
    restart: always
    env_file: .env
    build:
      context: ./front-end/
      args:
        REACT_APP_API_HOST: ${API_HOST}
    ports:
      - "80:80"
  backend:
    restart: always
    env_file: .env
    build: ./back-end/
    ports:
      - "3001:3000"
  database:
    restart: always
    image: mongo:latest
    volumes:
      - ./dbdata:/data/db
  objectstore:
    restart: always
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    env_file: .env
    volumes:
      - ./objects:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    expose:
      - 9000
      - 9001

volumes:
  dbdata:
  objects:
