version: "3.9"

services:
  frontend:
    restart: always
    env_file: .env
    build:
      context: ./front-end/
      args:
        REACT_APP_API_HOST: ${API_HOST}
    ports:
      - "80:80"
  backend:
    restart: always
    env_file: .env
    build: ./back-end/
    ports:
      - "3001:3000"
  database:
    restart: always
    image: mongo:latest
    volumes:
      - ./dbdata:/data/db

volumes:
  dbdata:
